### ISSUE TITLE
Correctly use DB transaction

### ISSUE THREAD

**Issue by TamalSaha** [cowrypay/dealer#32]
http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-10/

Also, we should try to avoid mutable rows. If rows are mutable, there must be history/log support to explain previous changes and original row value. 

Most importantly. we must not over write a row before reading it first. This is done using `select for update` feature. 
 - http://stackoverflow.com/a/16425603/244009
 - https://www.postgresql.org/docs/9.0/static/sql-select.html
 - https://github.com/go-xorm/xorm/search?utf8=%E2%9C%93&q=ForUpdate&type=

This can happen if processor is run with replica > 1 or processor is running with replica = 1 and merchant manually performs processing for a given customer.

**Comment by sadlil** [comment]
cc: @sanjid133
